apiVersion: v1
kind: Pod
metadata:
  labels:
    run: flask
  name: flask-jenkins
spec:
  containers:
  - image: 954503069243.dkr.ecr.eu-central-1.amazonaws.com/testing
    ports:
    - containerPort: 8080
    name: flask
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}